version: "3"
services:
  backend:
    build:
      context: ./hasura
    depends_on:
      - db
    env_file: ./hasura/.env
    ports:
      - 8080:8080
    volumes:
      - ./hasura:/backend-app
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata

  nextjs:
    build:
      context: ./frontend
    command: npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"

  db:
    image: postgres:11.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
